# Generated by Django 3.2.9 on 2021-12-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcarConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=50, verbose_name='Nome Paciente')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data', models.DateField(verbose_name='Data Consulta')),
                ('nome_medico', models.CharField(max_length=50, verbose_name='Nome Medico')),
                ('especialidade', models.CharField(max_length=50, verbose_name='Especialidade Medica')),
            ],
        ),
    ]
